"""empty message

Revision ID: 5fa85fdaf1d9
Revises: 
Create Date: 2017-05-04 16:50:59.602628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa85fdaf1d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('size_max', sa.Float(), nullable=True),
    sa.Column('size_min', sa.Float(), nullable=True),
    sa.Column('areas', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('acquisition_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disposal',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('size_max', sa.Float(), nullable=True),
    sa.Column('size_min', sa.Float(), nullable=True),
    sa.Column('lease', sa.String(length=120), nullable=True),
    sa.Column('rates', sa.Float(), nullable=True),
    sa.Column('service', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('post_code', sa.String(length=10), nullable=True),
    sa.Column('area_code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('email_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disposal')
    op.drop_table('acquisition_areas')
    op.drop_table('acquisition')
    # ### end Alembic commands ###
